### ISSUE TITLE
Basic auth example

### ISSUE THREAD

**Issue by BWibo** [zMoooooritz/stapy#20]
Does `stapy` support using a SensorThingsAPI protected by BasicAuth?
Can you give an example on how to use it? As `requests` library is use in the back, this should be possible.

**Comment by zMoooooritz** [comment]
Currently BasicAuth is not supported by stapy.
But it should be pretty easy to add that functionality (analog to the way the STA_URL is handled).

**Comment by zMoooooritz** [comment]
The requested BasicAuth has been implemented in #22 and is available with the newly released version [0.2.6](https://pypi.org/project/stapy/)
